# Generated by Django 3.1.5 on 2021-02-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mission', models.TextField(blank=True)),
                ('function', models.TextField(blank=True)),
                ('decreto', models.CharField(blank=True, max_length=50)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='objetivos.estructura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetivos.objetivos')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetivos.estructura')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
