# Generated by Django 3.1.5 on 2021-02-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0004_remove_estructura_adopt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipofuncion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('func', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
