# Generated by Django 3.1.5 on 2021-02-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0005_tipofuncion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tipofuncion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.tipofuncion')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='Objetivos',
            new_name='Objetivo',
        ),
        migrations.RenameModel(
            old_name='Preferencias',
            new_name='Preferencia',
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parama', models.FloatField()),
                ('paramb', models.FloatField()),
                ('paramc', models.FloatField()),
                ('paramd', models.FloatField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.indicador')),
            ],
            options={
                'ordering': ['createdat'],
            },
        ),
    ]
