# Generated by Django 3.1.5 on 2021-02-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0007_auto_20210212_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='vigencia',
            field=models.DateField(auto_now=True),
        ),
    ]
