# Generated by Django 3.1.5 on 2021-02-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0011_auto_20210212_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='detail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
