# Generated by Django 3.1.5 on 2021-02-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0012_auto_20210212_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipofuncion',
            options={},
        ),
    ]
