# Generated by Django 3.1.5 on 2021-02-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0013_auto_20210212_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipofuncion',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='parametro',
            name='vigencia',
            field=models.DateTimeField(),
        ),
    ]
