# Generated by Django 3.1.5 on 2021-02-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0014_auto_20210212_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametro',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='parametro',
            old_name='createdat',
            new_name='created',
        ),
    ]
