# Generated by Django 3.1.5 on 2021-02-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0015_auto_20210214_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametro',
            options={'ordering': ['created']},
        ),
    ]
