# Generated by Django 3.1.5 on 2021-02-20 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objetivos', '0016_auto_20210214_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_creator', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametro',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='param_creator', to='auth.user'),
            preserve_default=False,
        ),
    ]
