# Generated by Django 3.1.5 on 2021-04-21 22:02

from django.db import migrations
import django.db.models.deletion
import treewidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0017_auto_20210220_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='parent',
            field=treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='objetivos.objetivo'),
        ),
    ]
