# Generated by Django 3.1.5 on 2021-04-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0018_auto_20210421_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
