# Generated by Django 3.1.5 on 2021-04-22 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0019_auto_20210421_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='id_indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.indicador'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='tiene_indicador',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
