# Generated by Django 3.1.5 on 2021-04-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0020_auto_20210421_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='prefer',
            field=models.FloatField(default=1),
        ),
    ]
